version: '3.4'

services:

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin1

  mongo-express:
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin1
      ME_CONFIG_MONGODB_URL: mongodb://root:admin1@mongo:27017/
    
  stockmicroservices.stockmarketupdater:
    container_name: stockmarketupdater
    depends_on:
      - rabbitmq
    environment:
      - RabbitMq:RetryCount=5
      - RabbitMq:Hostname=rabbitmq
      - RabbitMq:Username=user
      - RabbitMq:Password=password

  stockmicroservices.api:
    container_name: stockapi
    depends_on:
      - mongo
      - rabbitmq
      - stockmicroservices.identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APIScope=StockMicroservicesAPI
      - IdentityServerUrl=http://stockidentityserver
      - RabbitMq:RetryCount=5
      - RabbitMq:Hostname=rabbitmq
      - RabbitMq:Username=user
      - RabbitMq:Password=password
      - Database:ConnectionString=mongodb://root:password@mongo:27017
      - Database:Hostname=mongo
      - Database:Name=stocks
      - Database:AdminUser=root
      - Database:AdminPassword=admin1
      - Database:DbUser=steam
      - Database:DbPassword=steam1
    ports:
      - "44300:80"

  stockmicroservices.apigateway:
    container_name: stockapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://stockidentityserver
      - APIScope=StockMicroservicesAPI
    ports:
      - "44405:80"
    depends_on:
      - stockmicroservices.api

  stockmicroservices.identityserver:
    container_name: stockidentityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
    ports:
      - "44401:80"
  

  stockmicroservices.webclient:
    container_name: stockwebclient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - stockmicroservices.api
      - stockmicroservices.identityserver
    ports:
      - "44100:80"
